# Model parameters
model:
  name: "CNN"

# Training parameters
training:
  batch_size: 128
  epochs: 10
  learning_rate: 0.001
  optimizer: "adam"

# Data parameters
data:
  dim: 5
  classes: 3
  window_size: 32
  random_state: 42
  stride: 1