# Model parameters
model:
  name: "TransformerFDD"  # или "TransformerFDD", "ResNet1D", "DualBranchFDD"

# Training parameters
training:
  batch_size: 64
  epochs: 10
  learning_rate: 0.0001
  optimizer: "adam"
  early_stopping_patience: 10

# Data parameters
data:
  dim: 5
  classes: 3
  window_size: 128
  random_state: 42
  stride: 1
  val_stride: 10