model:
  name: "LSTM_CNN_Hybrid"

training:
  batch_size: 64
  epochs: 20
  learning_rate: 0.0001
  optimizer: "adam"
  early_stopping_patience: 10

  use_scheduler: true
  scheduler_step_size: 6
  scheduler_gamma: 0.7

  loss_function: "focal"
  weight_strategy: "balanced_sqrt"
  focal_gamma: 4.0

data:
  dim: 5
  classes: 3
  window_size: 80
  random_state: 42
  stride: 1
  val_stride: 8
  split_strategy: "clustering_based"